###

GET {{HostAddress}}/v1/public/dummies

###

GET {{HostAddress}}/v1/public/dummies/1

###

POST {{HostAddress}}/v1/public/dummies
Content-Type: application/json

{
    "text" :"hola mundo"
}

###
